/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        /** Put Config */
        put: operations["put_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Config
         * @description Probe the real Amap endpoints so the UI can tell the user what works.
         */
        post: operations["verify_config_api_config_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Task */
        post: operations["preview_task_api_tasks_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Task */
        post: operations["run_task_api_tasks__task_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/aoi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Aoi */
        post: operations["run_aoi_api_tasks__task_id__aoi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Task */
        post: operations["pause_task_api_tasks__task_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Task */
        post: operations["resume_task_api_tasks__task_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Task */
        get: operations["export_task_api_tasks__task_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Records */
        get: operations["list_records_api_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the frontend and by tests.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AoiRequest */
        AoiRequest: {
            /** Record Ids */
            record_ids: number[];
        };
        /** Body_create_task_api_tasks_post */
        Body_create_task_api_tasks_post: {
            /** File */
            file: string;
            /** Name Column */
            name_column: string;
            /** Adname Column */
            adname_column?: string | null;
        };
        /** Body_preview_task_api_tasks_preview_post */
        Body_preview_task_api_tasks_preview_post: {
            /** File */
            file: string;
        };
        /**
         * ConfigPayload
         * @description Request body for PUT /api/config.
         */
        ConfigPayload: {
            /** Keys */
            keys?: string[];
            /**
             * Qps
             * @default 3
             */
            qps: number;
            /**
             * Daily Limit Per Key
             * @default 4500
             */
            daily_limit_per_key: number;
            /**
             * Default Region
             * @default 440100
             */
            default_region: string;
            /**
             * Sleep Every
             * @default 20
             */
            sleep_every: number;
            /**
             * Sleep Min Seconds
             * @default 3
             */
            sleep_min_seconds: number;
            /**
             * Sleep Max Seconds
             * @default 8
             */
            sleep_max_seconds: number;
            /**
             * Poi Page Size
             * @default 25
             */
            poi_page_size: number;
            /**
             * Poi Max Pages
             * @default 1
             */
            poi_max_pages: number;
            /**
             * Typecode Prefix
             * @default
             */
            typecode_prefix: string;
        };
        /** ConfigView */
        ConfigView: {
            /** Keys Masked */
            keys_masked: string[];
            /** Key Count */
            key_count: number;
            /** Qps */
            qps: number;
            /** Daily Limit Per Key */
            daily_limit_per_key: number;
            /** Default Region */
            default_region: string;
            /** Sleep Every */
            sleep_every: number;
            /** Sleep Min Seconds */
            sleep_min_seconds: number;
            /** Sleep Max Seconds */
            sleep_max_seconds: number;
            /** Poi Page Size */
            poi_page_size: number;
            /** Poi Max Pages */
            poi_max_pages: number;
            /** Typecode Prefix */
            typecode_prefix: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PreviewResult */
        PreviewResult: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[][];
            /** Suggested Name Column */
            suggested_name_column: string | null;
            /** Suggested Adname Column */
            suggested_adname_column: string | null;
            /** Name Confidence */
            name_confidence: string;
            /** Row Count Preview */
            row_count_preview: number;
        };
        /** RecordPage */
        RecordPage: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Items */
            items: components["schemas"]["RecordRow"][];
            /** Ids */
            ids: number[];
        };
        /** RecordRow */
        RecordRow: {
            /** Id */
            id: number;
            /** Task Id */
            task_id: number;
            /** Query Name */
            query_name: string;
            /** Match Level */
            match_level: string;
            /** Poi Name */
            poi_name: string;
            /** Poi Id */
            poi_id: string;
            /** Poi Type */
            poi_type: string;
            /** Typecode */
            typecode: string;
            /** Address */
            address: string;
            /** Adname */
            adname: string;
            /** Lng Gcj02 */
            lng_gcj02: number | null;
            /** Lat Gcj02 */
            lat_gcj02: number | null;
            /** Lng Wgs84 */
            lng_wgs84: number | null;
            /** Lat Wgs84 */
            lat_wgs84: number | null;
            /** Aoi Status */
            aoi_status: string;
            /** Aoi Area Ha */
            aoi_area_ha: number | null;
            /** Selected */
            selected: boolean;
        };
        /** RunResult */
        RunResult: {
            /** Started */
            started: boolean;
            /** Pending */
            pending: number;
        };
        /** TaskCreated */
        TaskCreated: {
            /** Task Id */
            task_id: number;
            /** Total */
            total: number;
            /** Skipped */
            skipped: number;
        };
        /** TaskView */
        TaskView: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Source Filename */
            source_filename: string;
            /** Total */
            total: number;
            /** Done */
            done: number;
            /** Failed */
            failed: number;
            /** Paused Reason */
            paused_reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyResult */
        VerifyResult: {
            /** Key Masked */
            key_masked: string;
            /** Key Status */
            key_status: string;
            /** Key Message */
            key_message: string;
            /** Geocode Status */
            geocode_status: string;
            /**
             * Geocode Location
             * @default
             */
            geocode_location: string;
            /**
             * Geocode Formatted Address
             * @default
             */
            geocode_formatted_address: string;
            /** Aoi Status */
            aoi_status: string;
            /** Aoi Message */
            aoi_message: string;
            /**
             * Aoi Hint
             * @default
             */
            aoi_hint: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    put_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_config_api_config_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResult"];
                };
            };
        };
    };
    preview_task_api_tasks_preview_post: {
        parameters: {
            query?: {
                max_rows?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_task_api_tasks_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"][];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_task_api_tasks_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_task_api_tasks__task_id__run_post: {
        parameters: {
            query?: {
                sync?: boolean;
            };
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_aoi_api_tasks__task_id__aoi_post: {
        parameters: {
            query?: {
                sync?: boolean;
            };
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AoiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_task_api_tasks__task_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_task_api_tasks__task_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_task_api_tasks__task_id__export_get: {
        parameters: {
            query?: {
                format?: string;
                crs?: string;
            };
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_api_records_get: {
        parameters: {
            query: {
                task_id: number;
                match_level?: string | null;
                adname?: string | null;
                keyword?: string | null;
                has_aoi?: boolean | null;
                selected?: boolean | null;
                page?: number;
                page_size?: number;
                all_ids_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
